{
  "compute_environment": "LOCAL_MACHINE",
  "distributed_type": "MULTI_GPU",
  "main_process_port": 29510,
  "downcast_bf16": true,
  "machine_rank": 0,
  "gpu_ids": "0,1",
  "main_training_function": "main",
  "mixed_precision": "no", # "no", "bf16"
  "num_machines": 1,
  "num_processes": 2,
  "rdzv_backend": "static",
  "same_network": true,
  "tpu_use_cluster": false,
  "tpu_use_sudo": false,
  "use_cpu": false
}